version: "3.9"
services:
  node1:
    image: node1:latest
    ports:
        - "3001:3000"
  node2:
    image: node1:latest
    ports:
        - "3002:3000"
  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    ports:
        - "80:80"
    depends_on:
        - node1
        - node2