version: "3.9"
services:
  node1:
    container_name: node-1
    build:
      context: ./app1
      dockerfile: Dockerfile  
    ports:
      - "3001:3000"
  node2:
    container_name: node-2
    build:
      context: ./app2
      dockerfile: Dockerfile 
    ports:
      - "3002:3000"
  nginx:
    container_name: nginx-lb
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - node1
      - node2